#camunda \u914D\u7F6E
camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      firstName: admin
    filter:
      create: All tasks
    job-execution:
      enabled: true
    metrics:
      enabled: false
      db-reporter-activate: false

#mysql \u6570\u636E\u5E93\u914D\u7F6E
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/approval?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
#\u670D\u52A1\u7AEF\u53E3
server:
  port: 8080
